language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: Z9QMablyjVRpL2LmCiLCi0SMzfoW+GzLhC/ZAXmuYkHSBBrgqMRup31JT52dvGjk+aKwwdYQZE+NzfvA8jSD9lV3ocuBxjuo1WwwpNuCJUp04c410g9I8mkzj0gp5AFv1ctCWzhShFJu1GUES/VigwDoFu7kQ0HsSI87fWLiLa4bz8a3ZE85nATL7RjCDW9ZPM/u1zlVeB2LKq4hoAM9Sdvx9pyTQpmTYNca2EYeFQOG6oGSov9CCj1P8Wp2ZyEaxYWEtDhLUQHvuXgvoIlDoy6MnvbbN6IOoAJbbTrDphkxtUjB9A4OX7MMJnXeH7VqdLCUgqGk7DHi9eeKRKkAnA6nTqh8qD91adFYZswRq/4y4KsCGGkHaQh/MOu+EkfnRW6Ru9zVnUS0smjvTzQFWrf4mzQzkcpgYyU3s3nN6LaQoyaErMj90Q6EHJ/MxjGb/GiORM0KdLnK9Wp9zNM8dPITmKaOstQmcmEgYu9y/EJi2rElzQpaamm2T/iGtQOKA9gEkHdC3gW2FG/H7/jR/Nym0CoHffIGAIvkprV+inYltMAh0vb/P8vTHUUQv4hKvoeQtrTUbxioEffSupM+cHUzRibfSfLNB/G5oTIAjzC1jo3bmgxM2+a8F/a8F+t8m8tnIq57RsBYQ4OYVrmcNbYvE7/tbJYWQBZvH094llk=
  app: dragonvaultapi
  on:
    repo: junkaiii/vaultdragon-challenge
